version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      MSSQL_SA_PASSWORD: "Secret1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    expose:
      - "1433"
    volumes:
      - ./logs:/var/opt/mssql/log/
      - ./data:/var/opt/mssql/data/
      - ./configs/mssql.conf:/var/opt/mssql/mssql.conf
    networks:
      - default

networks:
  default:
    name: mssql
